/**
 * Sumi shared contract. Both the overlay (browser) and the server/MCP (Node)
 * import from here. Keep this file dependency-free and browser-safe.
 */

export type AnnotationKind = "element" | "region";

/** What kind of change the person is asking for. Optional hint for the agent. */
export type Intent = "text" | "style" | "image" | "layout" | "remove" | "add" | "bug" | "other";

export const INTENTS: Intent[] = ["text", "style", "image", "layout", "remove", "add", "bug", "other"];

/**
 * draft        -> created in the overlay, not yet sent
 * sent         -> handed to Claude (via MCP wait/list or clipboard), awaiting action
 * needs-input  -> Claude asked a question (see `reply`); person should answer in the overlay
 * resolved     -> Claude reports it is done (`reply` holds a one-line summary)
 */
export type AnnotationStatus = "draft" | "sent" | "needs-input" | "resolved";

export interface Rect {
  /** Page (document) coordinates, not viewport. */
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ElementContext {
  /** Unique CSS selector, verified with querySelectorAll(...).length === 1 at capture time. */
  selector: string;
  tag: string;
  id?: string;
  classes: string[];
  /** ARIA role, explicit or implicit (heading, button, link, img, textbox, navigation, ...). */
  role?: string;
  /** Accessible-name approximation: aria-label, alt, visible text for heading/button/link, placeholder, title. */
  name?: string;
  /** Visible text, whitespace-collapsed, max 200 chars. */
  text?: string;
  /** outerHTML, max ~600 chars; long children collapsed to "…". */
  html: string;
  rect: Rect;
  /** Small computed-style subset: color, background-color, font-size, font-family, font-weight, line-height, padding, margin, border-radius, display, text-align. */
  styles: Record<string, string>;
  /** Interesting attributes only: href, src, alt, type, placeholder, name, aria-label, title, data-testid, role. */
  attributes: Record<string, string>;
  /** Nearest-first component chain when detectable, e.g. ["HeroTitle", "Hero", "App"]. */
  components?: string[];
  /**
   * Source location when detectable, e.g. "src/components/Hero.tsx:42:7" (line may be approximate).
   * In static mode: "<path relative to the served folder>:<line>:<col>" from the element's (or its
   * nearest ancestor's) data-sumi-src stamp.
   */
  source?: string;
  /** Nearest landmark description, e.g. 'section "Pricing"' or 'nav#main'. */
  landmark?: string;
  /** "html": a plain HTML file served by Sumi in static mode (source from data-sumi-src). */
  framework?: "react" | "vue" | "svelte" | "html" | "unknown";
}

export interface PageInfo {
  url: string;
  path: string;
  title: string;
  viewport: { width: number; height: number };
}

export interface Stroke {
  /** Freehand brush path in page coordinates, in drawing order. */
  points: { x: number; y: number }[];
  /** Brush diameter in CSS px. */
  size: number;
}

export interface RegionContext {
  /** Bounding box of the selection (marquee rectangle, or the stroke's bounds). */
  rect: Rect;
  /** How the region was drawn. Defaults to "marquee" when absent. */
  tool?: "marquee" | "brush";
  /** Present when tool === "brush". */
  stroke?: Stroke;
  /** Up to 12 meaningful elements intersecting the region (text, images, interactive). */
  elements: ElementContext[];
  /** Nearest common ancestor of the elements, when there is more than one. */
  container?: ElementContext;
}

export interface Annotation {
  /** Stable id, e.g. "a_k3j9x2". Generated by the overlay. */
  id: string;
  /** Display number shown on the pin, 1-based, assigned by the overlay per session. */
  n: number;
  kind: AnnotationKind;
  intent: Intent;
  /** What the person typed. May be empty for a pure "look at this" pin. */
  note: string;
  status: AnnotationStatus;
  createdAt: string;
  sentAt?: string;
  resolvedAt?: string;
  /** Claude's reply: a question when status is needs-input, a summary when resolved. */
  reply?: string;
  /** The person's answer to a needs-input question, if any. */
  answer?: string;
  page: PageInfo;
  /** Present when kind === "element". */
  target?: ElementContext;
  /** Present when kind === "region". */
  region?: RegionContext;
}

/**
 * "proxy":  Sumi reverse-proxies a running dev server (`target` is its URL).
 * "static": Sumi serves local files itself (`target` is the entry's file:// URL, `root` the folder).
 */
export type SessionMode = "proxy" | "static";

/** GET /__sumi/api/state */
export interface StateResponse {
  target: string;
  reviewUrl: string;
  mode: SessionMode;
  /** Absolute folder being served (static mode only). */
  root?: string;
  revision: number;
  annotations: Annotation[];
  /**
   * True while an agent is waiting for notes (a `/__sumi/api/wait` long-poll, i.e. `sumi wait`, or the
   * MCP `sumi_wait` tool is pending), or one ended less than 30 s ago.
   */
  agentListening: boolean;
}

/** Everything the server currently holds, used by the MCP server too. */
export interface SessionSummary {
  target: string;
  reviewUrl: string;
  mode: SessionMode;
  /** Absolute folder being served (static mode only). */
  root?: string;
  counts: Record<AnnotationStatus, number>;
}

/** Server-sent event `change` on GET /__sumi/api/events (static mode only). */
export interface LiveChange {
  /** Changed paths relative to the served folder. */
  files: string[];
  /** Every changed file is a .css file: stylesheets can be swapped without a reload. */
  css: boolean;
}
